# Generated by Django 5.1.2 on 2024-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
